language: php

php:
  - 7.2.0
  - 7.2.1
  - 7.2.2
  - 7.2.3
  - 7.2.4
  - 7.2.5
  - 7.2.6
  - 7.2.7
  - 7.2.8
  - 7.2.9
  - nightly

sudo: false

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --verbose